config/routes.rb
require "resque/server"
Rails.application.routes.draw do
	mount Resque::Server, :at => "/resque"
  
    root 'home#index'
    get 'about', to: 'home#about'

    get 'map', to: 'map#index'

    resources :dams, only: [:index, :show] do
    	get 'count_data', to: 'dams#count_data'
  	  resources :fish_counts, only: [:index, :show]
    end

    resources :fish, only: [:index, :show]
end

app/models/dam.rb
class Dam < ActiveRecord::Base
	extend FriendlyId
	require 'open-uri'
	friendly_id :name, use: :slugged
	validates :name, presence: true, uniqueness: true

	has_many :fish_counts
	has_many :fish, through: :fish_counts

	validates :name, presence: true, uniqueness: true

	def water_quality
		if self.code?
			puts "#{self.code}"
			string = URI.parse("http://www.nwd-wc.usace.army.mil/ftppub/water_quality/#{self.code}.txt")
			output = ""
			string.open {|f| f.each_line {|line| output << line + '<br/>'}}
			return output.html_safe
		else
			output = "No Water Quality Data Found"
		end
	end
end

app/models/fish.rb
class Fish < ActiveRecord::Base
	extend FriendlyId
	friendly_id :name, use: :slugged
	
  has_many :fish_counts

  validates :name, presence: true, uniqueness: true
	validates :avatar,
        attachment_content_type: { content_type: /\Aimage\/.*\Z/ },
        attachment_size: { less_than: 5.megabytes }

    has_attached_file :avatar, 
        styles: {thumb: '100x100>', med: '600x240>', full: '1200x480>'}

  def current_highest_counts
    fish_counts = self.fish_counts.for_year(Date.today.year).limit(15).order(count_date: :desc)
    fish_counts.order(count: :desc)
  end
end

app/models/fish_count.rb
class FishCount < ActiveRecord::Base
	belongs_to :fish 
	belongs_to :dam

	# Date validation will limit the feed to only pull in the first first per date.
	# Will need to refactor in order to validate all three fields are unique (fish, dam, date)
	validates :dam_id, presence: true
	validates :fish_id, presence: true
	validates :count_date, presence: true
	validates :count_date, :uniqueness => { :scope => [:dam_id, :fish_id] }

	scope :for_year, lambda {|year| where("count_date >= ? and count_date <= ?", "#{year}-01-01", "#{year}-12-31")}


	def format_date
    	self.count_date.strftime("%B %d, %Y")
    end

    #orders the scoped year by count_date
    def ordered_year_count
    	FishCount.for_year(Date.today.year).order(count_date: :desc)
    end

    #returns the last count for that species -- is the run is increasing or decreasing
    #could be cleaner...?
    def last_count
    	ordered_count = self.ordered_year_count.where("dam_id = ? AND fish_id = ?", self.dam_id, self.fish_id)
    	range = ordered_count.where(:count_date => self.count_date.ago(1.week)..self.count_date)
    	begin
    		count = range[1].count
    	rescue
    		return false
    	end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dams_controller.rb
class DamsController < ApplicationController

	def index
		@dams = Dam.all.order(id: :asc)
	end

	def show
		@dams = Dam.all.order(id: :asc)
		@dam = Dam.includes(:fish_counts, :fish).friendly.find(params[:id])
		@fish_counts = @dam.fish_counts.for_year(Date.today.year).order(count_date: :desc).paginate(:page => params[:page], :per_page => 20, :total_entries => 500)
		@water_quality = @dam.water_quality
	end

	def count_data
		@dam = Dam.includes(:fish_counts, :fish).friendly.find(params[:dam_id])
		fish_counts = @dam.fish_counts.for_year(Date.today.year).limit(15).order(count_date: :desc)
		@daily_total = fish_counts.where("count_date = ?", fish_counts.first.count_date)

		respond_to do |format|
			format.json {
				render json: @daily_total.to_json(:include => :fish)
			}
		end
	end
end

app/controllers/fish_controller.rb
class FishController < ApplicationController

	def index
		@fishes = Fish.all.order(name: :asc)
	end

	def show
		@fishes = Fish.all.order(name: :asc)
		@fish = Fish.includes(:fish_counts).friendly.find(params[:id])
    @fish_counts = @fish.current_highest_counts
		@dam = Dam.includes(:fish_counts, :fish)
	end

	def edit
		@fish = Fish.friendly.find(params[:id])
	end
    
    def update
    	@fish = Fish.friendly.find(params[:id])
    	respond_to do |format|
      		if @fish.update(fish_params)
        		format.html { redirect_to @fish, notice: 'Fish was successfully updated.' }
        		format.json { head :no_content }
      		else
        		format.html { render action: 'edit' }
        		format.json { render json: @fish.errors, status: :unprocessable_entity }
      		end
    	end
  	end

	private 

	    def fish_params
	      params.require(:fish).permit(:name, :avatar)
	    end
end

app/controllers/fish_counts_controller.rb
class FishCountsController < ApplicationController

	def index
	end

	def show
	end
	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end

	def about
	end

end

app/controllers/map_controller.rb
class MapController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dams_helper.rb
module DamsHelper
end

app/helpers/fish_counts_helper.rb
module FishCountsHelper
end

app/helpers/fish_helper.rb
module FishHelper

  def find_dam(fish_count)
    Dam.find(fish_count.dam_id)
  end
  
end

app/views/dams/_dam_graph.html.erb
<div class = 'container fill'>
  <div class="sk-folding-cube">
    <div class="sk-cube1 sk-cube"></div>
    <div class="sk-cube2 sk-cube"></div>
    <div class="sk-cube4 sk-cube"></div>
    <div class="sk-cube3 sk-cube"></div>
  </div>
	<div id='show_graph'>
  </div>
  <div id='mobile_graph'>
  </div>
  <div id='try-later'>
    <p>This graph is not yet ready for mobile. Try flipping your phone horizontal.</p>
  </div>
</div>


<script>

var rel_path = ("<%= escape_javascript @dam.slug %>" + "/count_data.json");

function appendMobileChart(count_data) {

  var dataset = count_data;
  var width = 200;
  var height = 200;
  var radius = Math.min(width, height) / 2;
  var donutWidth = 37.5;
  var legendRectSize = 9;                             
  var legendSpacing = 4;                               

  var color = d3.scale.category20c(); 

  var svg = d3.select('#mobile_graph')
    .append('svg')
    .attr('width', "100%")
    .attr('height', "100%")
    .append('g')
    .attr('transform', 'translate(' + (width / 2) + 
      ',' + (height / 2) + ')');

  var arc = d3.svg.arc()
    .innerRadius(radius - donutWidth)
    .outerRadius(radius);

  var pie = d3.layout.pie()
    .value(function(d) { return d.count; })
    .sort(null);

  var path = svg.selectAll('path')
    .data(pie(dataset))
    .enter()
    .append('path')
    .attr('d', arc)
    .attr('fill', function(d, i) { 
      return color((d.data.fish.name) + ":" + (d.data.count));
    });
    
  var legend = svg.selectAll('.legend')                
    .data(color.domain())                              
    .enter()                                           
    .append('g')                                       
    .attr('class', 'legend')                           
    .attr('transform', function(d, i) {                
      var height = legendRectSize + legendSpacing;     
      var offset =  height * color.domain().length / 2;
      var horz = -2 * legendRectSize;                  
      var vert = i * height - offset;                  
      return 'translate(' + horz + ',' + vert + ')';   
    });                                                

  legend.append('rect')                                
    .attr('width', legendRectSize)                     
    .attr('height', legendRectSize)                    
    .style('fill', color)                              
    .style('stroke', color);                           
    
  legend.append('text')                                
    .attr('x', legendRectSize + legendSpacing)         
    .attr('y', legendRectSize - legendSpacing)         
    .text(function(d) { return d; });
};


function appendChart(count_data) {

  var dataset = count_data;
  var width = 400;
  var height = 400;
  var radius = Math.min(width, height) / 2;
  var donutWidth = 75;
  var legendRectSize = 18;                             
  var legendSpacing = 4;                               

  var color = d3.scale.category20c(); 

  var svg = d3.select('#show_graph')
    .append('svg')
    .attr('width', "100%")
    .attr('height', "100%")
    .append('g')
    .attr('transform', 'translate(' + (width / 2) + 
      ',' + (height / 2) + ')');

  var arc = d3.svg.arc()
    .innerRadius(radius - donutWidth)
    .outerRadius(radius);

  var pie = d3.layout.pie()
    .value(function(d) { return d.count; })
    .sort(null);

  var path = svg.selectAll('path')
    .data(pie(dataset))
    .enter()
    .append('path')
    .attr('d', arc)
    .attr('fill', function(d, i) { 
      return color((d.data.fish.name) + ":" + (d.data.count));
    });

  var legend = svg.selectAll('.legend')                
    .data(color.domain())                              
    .enter()                                           
    .append('g')                                       
    .attr('class', 'legend')                           
    .attr('transform', function(d, i) {                
      var height = legendRectSize + legendSpacing;     
      var offset =  height * color.domain().length / 2;
      var horz = -2 * legendRectSize;                  
      var vert = i * height - offset;                  
      return 'translate(' + horz + ',' + vert + ')';   
    });                                                

  legend.append('rect')                                
    .attr('width', legendRectSize)                     
    .attr('height', legendRectSize)                    
    .style('fill', color)                              
    .style('stroke', color);                           
    
  legend.append('text')                                
    .attr('x', legendRectSize + legendSpacing)         
    .attr('y', legendRectSize - legendSpacing)         
    .text(function(d) { return d; });
  
};

$.ajax({
           beforeSend: function() {
            $(".sk-folding-cube").show();
           },
           type: "GET",
           contentType: "application/json; charset=utf-8",
           url: rel_path,
           dataType: 'json',
           success: function (data) {
               count_data = data;
               console.log(data);
               appendChart(count_data);
               appendMobileChart(count_data);
               $("#show_graph").hide();
               $("#show_graph").delay(1500).fadeIn(350);
               $("#mobile_graph").hide();
               $("#mobile_graph").delay(1500).slideUp(300).fadeIn(350);
               $(".sk-folding-cube").delay(1500).slideUp(300);
           },
           error: function (result) {
               console.log("Failed to Load");
           }
       });

</script>

app/views/dams/_fish_count.html.haml
.panel.panel-default.text-block-1
  .panel-heading.text-center
    %h3.title-text 
      = @dam.name
    .row
      %em change from previous count:
    .row
      %span.badge.custom-badges.increasing-badge
        %span.glyphicon.glyphicon-menu-up
      Up from yesterday 
      %span.badge.custom-badges.decreasing-badge
        %span.glyphicon.glyphicon-menu-down
      Down from yesterday 
      %span.badge.custom-badges.same-badge
        %span.glyphicon.glyphicon-minus
      No Change 
      %span.badge.custom-badges.notfound-badge
        %span.glyphicon.glyphicon-ban-circle
      Not Found 
    .row
      .nav
        %ul.pagination
          = will_paginate @fish_counts, renderer: BootstrapPagination::Rails
  - @fish_counts.each do |count|
    %p.list-group-item
      - if count.last_count == false
        %span.badge.custom-badges.notfound-badge
          %span.glyphicon.glyphicon-ban-circle
      - else
        - if count.count > count.last_count
          %span.badge.custom-badges.increasing-badge
            %span.glyphicon.glyphicon-menu-up
        - elsif count.count < count.last_count
          %span.badge.custom-badges.decreasing-badge
            %span.glyphicon.glyphicon-menu-down
        - else
          %span.badge.custom-badges.same-badge
            %span.glyphicon.glyphicon-minus
      %span.badge.custom-badges.fishcount-badge
        = count.count
      %em Species:
      %strong
        = link_to "#{count.fish.name}", fish_url(count.fish)
      %br
      %em Date Observed:
      %strong
        = count.count_date.strftime("%B %d %Y")

app/views/dams/_sidebar.html.haml
.col-md-2
  .panel.panel-default.text-block-1
    .panel-heading.butntext.text-center
      = link_to "All Dams", dams_path
    %ul.list-group
      - @dams.each do |dam|
        %li.list-group-item.title-text
          = link_to "#{dam.name}", dam_url(dam)
    .panel-heading.butntext.text-center
      = link_to "Home", root_path

app/views/dams/_water_quality.html.haml
%p
  = @water_quality

app/views/dams/index.html.haml
= render :partial => "sidebar"
.col-md-10
  .text-block-1
    = render :partial => "home/home_map.html.erb"

app/views/dams/show.html.haml
.sidebar-block
  = render :partial => "sidebar"
.col-md-5.dam-graph-block
  .panel.panel-default.text-block-1
    .panel-heading.text-center
      Data From Our Most Recent Count
    = render :partial => "dam_graph"
  .panel.panel-default.text-block-1.quality-block
    %h4.text-center
      / %h2 Water Quality Data
      %button.btn.btn-info{"data-target" => "#demo", "data-toggle" => "collapse", :type => "button"} Show Water Quality Data
      #demo.collapse
        %p.text-left
          = @water_quality
.col-md-5.fish-count-block
  = render :partial => "fish_count"

app/views/fish/_fish_index_graph.html.erb
<div class = 'container fill'>
  <div class="sk-folding-cube">
    <div class="sk-cube1 sk-cube"></div>
    <div class="sk-cube2 sk-cube"></div>
    <div class="sk-cube4 sk-cube"></div>
    <div class="sk-cube3 sk-cube"></div>
  </div>
  <div id='fish_index_graph'>
    <div id="chart"></div>
  </div>
  <div id='try-later'>
    <p>This graph is not yet ready for mobile. Try flipping your phone horizontal.</p>
  </div>
</div>

</script>

app/views/fish/_sidebar.html.haml
.col-md-2
  .panel.panel-default.text-block-1
    .panel-heading.butntext.text-center
      = link_to "All Fish", fish_index_path
    %ul.list-group
      - @fishes.each do |fish|
        %li.list-group-item.title-text
          = link_to "#{fish.name}", fish_url(fish)
    .panel-heading.butntext.text-center
      = link_to "Home", root_path

app/views/fish/edit.html.erb
<!-- <%= form_for(@fish, multipart: true) do |f| %>
  <% if @fish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fish.errors.count, "error") %> prohibited this fish from being saved:</h2>

      <ul>
      <% @fish.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :avatar %>
    <%= f.file_field :avatar %>
  </div>
  <div class="actions">
   <%= f.submit 'Upload a fish avatar' %>
   <%= link_to 'Nevermind', fish_path, class: 'button' %>
  </div>
<% end %> -->

app/views/fish/index.html.haml
.sidebar-block
  = render 'sidebar'
.col-md-10.dam-graph-block
  .panel.panel-default.text-block-1
    .panel-heading.text-center
      Current Salmon Runs
    - @fishes.each do |fish|
      - current_highest = fish.current_highest_counts.first
      - second_highest = fish.current_highest_counts.second
      - dam = find_dam(current_highest)
      - second_dam = find_dam(second_highest)
      %p
        %strong
          = fish.name
        %em
          = current_highest.format_date 
          highest count
        |
        = current_highest.count
        |
        = link_to "#{dam.name}", dam_url(dam)
        |
        %em
          second highest:
        |
        = second_highest.count
        |
        = link_to "#{second_dam.name}", dam_url(second_dam)

app/views/fish/show.html.haml
.sidebar-block
  = render :partial => "sidebar"
.col-md-5
  .panel.panel-default.text-block-1
    .panel-heading.text-center
      = @fish.name
    - @fish_counts.each do |fish|
      - dam = find_dam(fish)
      %p
        %strong
          = fish.count
        %em
          made it through
          = link_to "#{dam.name}", dam_url(dam)
          on
          = fish.format_date

app/views/home/_home_map.html.erb
<div class = 'container fill'>
	<div id='map' class='home-map'>
	</div>
</div>


<script>
	newMap("<%= escape_javascript(ENV["MAPBOX_TOKEN"]) %>", 6);
</script>

app/views/home/about.html.haml
%body.bg-about
  .container
    .col-md-6.col-md-offset-3
      .text-block-2.bio.title-text
        %h2.text-center
          About
        %p
          Passive capture is a project created by 
          = link_to "Stuart Illson", "http://www.stuartillson.com", :target => "_blank"
          to enable greater insight & visualization into anadromous fish runs in the Pacific Northwest.
        %p 
          Soon we will launch a dashboard and statistics for each of the dams marked on a map. Farther down the line we will analyze data spanning the past several decades to allow us to project fish counts, large-scale fish kills, and the rate at which our native fish move through the Columbia River watershed. 

        %p 
          Check back soon, or get in touch to collaborate:
          %em anadromousdata@gmail.com

app/views/home/index.html.haml
.container
  .row
    .col-md-4.col-sm-4
      = link_to dams_path, :class => 'butntext' do
        .butn.paper-raise
          dams
    .col-md-4.col-sm-4
      = link_to fish_index_path, :class => 'butntext' do
        .butn.paper-raise 
          fish
    .col-md-4.col-sm-4
      = link_to map_path, :class => 'butntext' do
        .butn.paper-raise
          map

.container
  .text-block-1
    %h2.text-center.butntext
      overview of dams
    %p.text-center.butntext
      select a dam below to view the daily fish counts
    = render :partial => "home_map"

#parralax
  #parralax-content
    .col-md-4.col-md-offset-4
      .text-block-2
        %h3.text-center.butntext
          %em Spawn Until You Die


      

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default
  .container
    .navbar-header
      %h4.navbar-text
        = link_to 'passive-capture', root_path
    %ul.nav.navbar-nav.navy-items.navbar-right
      %li.navbar-text
        = link_to 'blog', '#'
      %li.navbar-text
        = link_to 'about', about_path
      
      

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    = favicon_link_tag 'favicon.ico'
    %script{:src => "https://api.tiles.mapbox.com/mapbox.js/v2.2.1/mapbox.js"}
    %link{:href => "https://api.tiles.mapbox.com/mapbox.js/v2.2.1/mapbox.css", :rel => "stylesheet"}/
    %script{:src => "https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js"}
    %title= content_for?(:title) ? yield(:title) : 'Passive-Capture'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Passive-Capture'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield
    %footer
      = render 'layouts/footer'

app/views/map/_full_map.html.erb
<div class = 'full'>
  <div id='map'>
  </div>
</div>


<script>

L.mapbox.accessToken = "<%= escape_javascript(ENV["MAPBOX_TOKEN"]) %>";
  
var map = L.mapbox.map('map', 'sillson.lhm0n06m').setView([46.24, -120.14], 7);
 
var col_polyline = L.polyline([]).addTo(map);
var col_length = columbiaNorthLine.length
var pointsAdded = 0;
add();
function add() {
    // `addLatLng` takes a new latLng coordinate and puts it at the end of the line. To draw multiple lines, will have to switch out Columbia North Line for something dynamic.
    col_polyline.addLatLng(
        L.latLng(columbiaNorthLine.shift())
        );
   
    if (++pointsAdded < col_length) window.setTimeout(add, 50);
    // Panning? Gives me a headache
    // map.setView([46.24, (line_points.shift())[1]], 6);
}
</script>

app/views/map/index.html.haml
= render :partial => "full_map"